[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_marketplace = "3vtF9uetZjwXNHeptSGS5nBEBYwrwmDXAchzzjnpkS9h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/igdeman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
